CREATED_POST_SUCCESSFUL_MESSAGE = "The post was created successfully"
GET_POST_SUCCESSFUL_MESSAGE = "The post were successfully retrieved"
POST_NOT_FOUND_MESSAGE = "The post was not found"
UPDATE_POST_SUCCESSFUL_MESSAGE = "The post was successfully updated"
POSTS_NOT_FOUND_MESSAGE = "A task with the provided id does not exist"
POST_DELETED_SUCCESSFUL_MESSAGE = "The task was successfully deleted"