CREATED_TASK_SUCCESSFUL_MESSAGE = "Task has been created successfully"
GET_TASKS_SUCCESSFUL_MESSAGE = "Tasks have been successfully retrieved"
UPDATE_TASK_SUCCESSFUL_MESSAGE = "Task has been updated successfully"
TASK_NOT_FOUND_MESSAGE = "A task with the provided id does not exist"
TASK_DELETED_SUCCESSFUL_MESSAGE = "Task has been deleted successfully"