"""removed redunandant about in the mentor manager model

Revision ID: 08362f395330
Revises: 8691a96489bf
Create Date: 2023-05-09 16:14:14.764184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08362f395330'
down_revision = '8691a96489bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
