"""Added is active flag to message model

Revision ID: 0c47db4bbb13
Revises: da7292bbdbf0
Create Date: 2023-05-06 13:28:02.309518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c47db4bbb13'
down_revision = 'da7292bbdbf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_active')
    # ### end Alembic commands ###
