"""Created user Conversation Relationship

Revision ID: 104ecf84a40f
Revises: bf806ba2ee7d
Create Date: 2023-05-01 23:37:51.906069

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '104ecf84a40f'
down_revision = 'bf806ba2ee7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_social_links_id'), 'social_links', ['id'], unique=False)
    op.create_unique_constraint(None, 'social_links', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_links', type_='unique')
    op.drop_index(op.f('ix_social_links_id'), table_name='social_links')
    # ### end Alembic commands ###
