"""Added messages associations

Revision ID: 12313f8d1a75
Revises: d7cfeeb2de58
Create Date: 2023-05-03 01:16:18.683277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12313f8d1a75'
down_revision = 'd7cfeeb2de58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'receiver_id')
    op.drop_column('messages', 'sender_id')
    # ### end Alembic commands ###
