"""Added is default flag to message model

Revision ID: 1762e26440e7
Revises: 0c47db4bbb13
Create Date: 2023-05-06 13:46:58.122639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1762e26440e7'
down_revision = '0c47db4bbb13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
