"""Fixed Typo messages associations

Revision ID: 1811c401371b
Revises: 12313f8d1a75
Create Date: 2023-05-03 01:46:32.506452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1811c401371b'
down_revision = '12313f8d1a75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
