"""added sent and received messages.

Revision ID: 3e9dccfc0a86
Revises: 6b2095777a08
Create Date: 2023-05-09 02:14:12.982082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9dccfc0a86'
down_revision = '6b2095777a08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
