"""removed roles from Mentor Manager

Revision ID: 43632e2b250a
Revises: 7b53f8b00746
Create Date: 2023-05-09 01:19:07.629254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43632e2b250a'
down_revision = '7b53f8b00746'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
