"""added join condition to program

Revision ID: 49db431aa2b0
Revises: 43632e2b250a
Create Date: 2023-05-09 01:21:45.943161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49db431aa2b0'
down_revision = '43632e2b250a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
