"""added sent and received messages.

Revision ID: 531da78846da
Revises: 9f5b313a73f0
Create Date: 2023-05-09 01:56:34.766954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531da78846da'
down_revision = '9f5b313a73f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
