"""added sent and received messages.

Revision ID: 591215295d1c
Revises: c796dc945efd
Create Date: 2023-05-09 02:08:24.498787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591215295d1c'
down_revision = 'c796dc945efd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
