"""Fixed Typo messages associations

Revision ID: 6158b616a6a1
Revises: b482819d0b10
Create Date: 2023-05-03 02:04:52.389411

"""

# revision identifiers, used by Alembic.
revision = '6158b616a6a1'
down_revision = 'b482819d0b10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
