"""added sent and received messages.

Revision ID: 6b2095777a08
Revises: 591215295d1c
Create Date: 2023-05-09 02:12:21.969785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2095777a08'
down_revision = '591215295d1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
