"""Added about model

Revision ID: 7b53f8b00746
Revises: c440d705a08e
Create Date: 2023-05-09 01:18:00.680263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b53f8b00746'
down_revision = 'c440d705a08e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
