"""added about relationships

Revision ID: 8691a96489bf
Revises: 8b89fa96784d
Create Date: 2023-05-09 15:48:29.138668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8691a96489bf'
down_revision = '8b89fa96784d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abouts', sa.Column('mentor_id', sa.Integer(), nullable=True))
    op.add_column('abouts', sa.Column('mentor_manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'abouts', 'mentors', ['mentor_id'], ['id'])
    op.create_foreign_key(None, 'abouts', 'mentor_managers', ['mentor_manager_id'], ['id'])
    op.drop_column('mentor_managers', 'about')
    op.drop_column('mentors', 'about')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('about', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mentor_managers', sa.Column('about', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'abouts', type_='foreignkey')
    op.drop_constraint(None, 'abouts', type_='foreignkey')
    op.drop_column('abouts', 'mentor_manager_id')
    op.drop_column('abouts', 'mentor_id')
    # ### end Alembic commands ###
