"""added foreign key fields.

Revision ID: 8b89fa96784d
Revises: af05d7641ae1
Create Date: 2023-05-09 02:31:20.951214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b89fa96784d'
down_revision = 'af05d7641ae1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
