"""Alembic Tasks Created

Revision ID: 8f60e6cce3c9
Revises: fe8ea9fb3a4d
Create Date: 2023-04-27 12:01:50.721622

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8f60e6cce3c9'
down_revision = 'fe8ea9fb3a4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor_managers', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mentor_managers', 'tasks', ['task_id'], ['id'])
    op.add_column('mentors', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mentors', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentors', type_='foreignkey')
    op.drop_column('mentors', 'task_id')
    op.drop_constraint(None, 'mentor_managers', type_='foreignkey')
    op.drop_column('mentor_managers', 'task_id')
    # ### end Alembic commands ###
