"""added sent and received messages.

Revision ID: 9f5b313a73f0
Revises: d6ec58f1d3c8
Create Date: 2023-05-09 01:49:54.056431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5b313a73f0'
down_revision = 'd6ec58f1d3c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
