"""New Conversations Link

Revision ID: a58ef99360d3
Revises: 104ecf84a40f
Create Date: 2023-05-02 16:50:49.954220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58ef99360d3'
down_revision = '104ecf84a40f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
