"""Added about model

Revision ID: a7f6dd01585c
Revises: 1762e26440e7
Create Date: 2023-05-09 00:55:20.186942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f6dd01585c'
down_revision = '1762e26440e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_mentor_manager_id_fkey', 'roles', type_='foreignkey')
    op.drop_constraint('roles_mentor_id_fkey', 'roles', type_='foreignkey')
    op.drop_column('roles', 'mentor_id')
    op.drop_column('roles', 'mentor_manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('mentor_manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('mentor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('roles_mentor_id_fkey', 'roles', 'mentors', ['mentor_id'], ['id'])
    op.create_foreign_key('roles_mentor_manager_id_fkey', 'roles', 'mentor_managers', ['mentor_manager_id'], ['id'])
    # ### end Alembic commands ###
