"""added sent and received messages.

Revision ID: af05d7641ae1
Revises: 3e9dccfc0a86
Create Date: 2023-05-09 02:30:31.137621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af05d7641ae1'
down_revision = '3e9dccfc0a86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
