"""Fixed Typo messages associations

Revision ID: b482819d0b10
Revises: f1e83bddb90b
Create Date: 2023-05-03 01:51:42.193042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b482819d0b10'
down_revision = 'f1e83bddb90b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
