"""New Conversations Link

Revision ID: bbe28d4a49cd
Revises: a58ef99360d3
Create Date: 2023-05-02 17:38:34.190762

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bbe28d4a49cd'
down_revision = 'a58ef99360d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_participant_conversation_association_id', table_name='participant_conversation_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_participant_conversation_association_id', 'participant_conversation_association', ['id'],
                    unique=False)
    # ### end Alembic commands ###
