"""Added task open or completed state.

Revision ID: bf806ba2ee7d
Revises: 8f60e6cce3c9
Create Date: 2023-04-29 11:24:34.466470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf806ba2ee7d'
down_revision = '8f60e6cce3c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('open', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'open')
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###
