"""Added about model

Revision ID: c440d705a08e
Revises: a7f6dd01585c
Create Date: 2023-05-09 01:14:19.100402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c440d705a08e'
down_revision = 'a7f6dd01585c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    # ### end Alembic commands ###
