"""added sent and received messages.

Revision ID: c796dc945efd
Revises: b4c537234a72
Create Date: 2023-05-09 02:02:57.797920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c796dc945efd'
down_revision = 'b4c537234a72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
