"""added sent and received messages.

Revision ID: d6ec58f1d3c8
Revises: 49db431aa2b0
Create Date: 2023-05-09 01:47:13.833819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ec58f1d3c8'
down_revision = '49db431aa2b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
