"""association tables not inheriting from Abstract base.

Revision ID: d7cfeeb2de58
Revises: 83195a444300
Create Date: 2023-05-02 17:55:42.162321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7cfeeb2de58'
down_revision = '83195a444300'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant_conversation_association', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_conversation_association', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
