"""Fixed Typo messages associations

Revision ID: f1e83bddb90b
Revises: 1811c401371b
Create Date: 2023-05-03 01:49:36.555966

"""

# revision identifiers, used by Alembic.
revision = 'f1e83bddb90b'
down_revision = '1811c401371b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
