"""Alembic initial revision

Revision ID: fe8ea9fb3a4d
Revises: 5f28072965c1
Create Date: 2023-04-25 18:56:45.831499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8ea9fb3a4d'
down_revision = '5f28072965c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
