PROFILE_CREATED_SUCCESS_MESSAGE = "Profile created successfully"
PROFILE_DOES_NOT_EXIST_MESSAGE = "Profile does not exist"
PROFILE_REQUEST_SUCCESS_MESSAGE = "Profile retrieved successfully"
PROFILE_EXISTS_MESSAGE = "A profile for this user already exists"
INVALID_USER_PARAMETER = "Invalid user id parameter"
INVALID_PROFILE_PARAMETER = "Invalid profile id parameter"
